# Generated by Django 3.0.8 on 2020-09-09 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20200909_0309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserDeliveryInfo',
        ),
    ]
