# Generated by Django 3.0.8 on 2020-08-23 20:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Abc', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Abc', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None),
        ),
    ]
