# Generated by Django 3.0.8 on 2020-08-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200823_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=30, null='False'),
            preserve_default='False',
        ),
    ]
