# Generated by Django 3.0.8 on 2020-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20200901_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
