# Generated by Django 3.0.8 on 2020-09-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200918_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roast_level',
            field=models.CharField(default='', max_length=30),
        ),
    ]
