# Generated by Django 3.0.8 on 2020-09-25 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200924_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='star_percentage',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='CustomUserRating',
        ),
    ]
