# Generated by Django 3.0.8 on 2020-09-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200925_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='star_percentage',
            field=models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
