# Generated by Django 3.0.8 on 2020-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200925_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
