# Generated by Django 3.0.8 on 2020-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='description_2',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
