# Generated by Django 3.0.8 on 2020-07-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200731_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cupping_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='good',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
