# Generated by Django 3.0.8 on 2020-07-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200731_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
    ]
