# Generated by Django 3.0.8 on 2020-07-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200731_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodimage',
            old_name='product',
            new_name='good',
        ),
    ]
