# Generated by Django 3.0.8 on 2020-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200731_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(default='Enter general description'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description_2',
            field=models.TextField(default='Add product origin description, history, other details...'),
        ),
        migrations.AlterField(
            model_name='good',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='good',
            name='roast_level',
            field=models.CharField(default='e.g. dark', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Enter general description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=models.TextField(default='Add product origin description, history, other details...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='roast_level',
            field=models.CharField(default='e.g. dark', max_length=30),
        ),
    ]
