# Generated by Django 3.0.8 on 2020-07-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200731_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodimage',
            name='good',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='GoodImage',
        ),
    ]
