# Generated by Django 3.0.8 on 2020-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200812_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=3, null=True),
        ),
    ]
